services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: http://backend:8080/api/v1/

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://<RENDER_DATABASE_HOST>:<RENDER_DATABASE_PORT>/<RENDER_DATABASE_NAME>
      - key: DB_USER
        value: <RENDER_DATABASE_USER>
      - key: DB_PASSWORD
        value: <RENDER_DATABASE_PASSWORD>
      - key: PORT
        value: 8080
      - key: DB_DDL_AUTO
        value: create

databases:
  - name: mysql
    plan: free
    databaseName: trips
